# https://developer.chrome.com/docs/extensions/mv2/background_pages/
background:
    
    # Script definition
    # @property string output, path of compiled script. it's appear in manifest.json
    # @property string|array input
    main:
        output: app/background.js
        input:
            - app/background/index.js
    
    # other:
    #     output: app/backgroundOther.js
    #     input: app/background/other.js
        