locales:

    # Translation directory
    # @var null|string
    # @default /src/translations/
    path: ~

    # Default Locale - optional
    # https://developer.chrome.com/docs/extensions/mv2/manifest/default_locale/
    default: en