# Manifest Version
manifest:

    # Manifest Version - required
    # @var int 2|3
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/manifest_version/
    version: 2

# Extension
extension:

    # Extension Name - optional
    # maximum of 45 characters
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/name/#name
    name: __MSG_ExtensionName__ 

    # Extension Short Name - optional
    # maximum of 12 characters recommended
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/name/#short_name
    short_name: ~

    # Extenstion description - optional
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/description/
    description: __MSG_ExtensionDescription__

    # Extension Version - optional
    # Default: Package version
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/version/
    version: ~

    # Author
    # @var string Name of the author of the extension
    # @default Package Author
    author: ~

    # Homepage URL
    # @var string the url of Homepage of the extension
    # @default Null
    url: ~

# UI Icons
# @info https://developer.chrome.com/docs/extensions/mv2/manifest/icons/
icons:
    "16": assets/icons/icon16.png
    "64": assets/icons/icon64.png
    "128": assets/icons/icon128.png

# Internationalisation
locales:

    # Default Locale - optional
    # https://developer.chrome.com/docs/extensions/mv2/manifest/default_locale/
    default: en

app:

    # https://developer.chrome.com/docs/extensions/mv2/background_pages/
    background:
        persistent: true
        scripts:
            - app/background.js
    
    # https://developer.chrome.com/docs/extensions/mv2/content_scripts/
    content:
        
        scripts:
            - app/content.js

        stylesheets:
            # - assets/stylesheets/content.css

        # Specify Frame
        # https://developer.chrome.com/docs/extensions/mv2/content_scripts/#frames
        all_frames: true

        # Run Time - optional
        # document_idle | document_start | document_end
        # https://developer.chrome.com/docs/extensions/mv2/content_scripts/#run_time
        run_time: document_end

        # https://developer.chrome.com/docs/extensions/mv2/content_scripts/#matchAndGlob
        matches:
            include: 
                - http://*/*
                - https://*/*
            exclude: ~
        
        # https://developer.chrome.com/docs/extensions/mv2/content_scripts/#matchAndGlob
        globs:
            include: ~
            exclude: ~

    # https://developer.chrome.com/docs/extensions/reference/browserAction/
    browser_action:

        # Popup
        # https://developer.chrome.com/docs/extensions/reference/browserAction/#popup
        popup: pages/popup/index.html

        # Tooltip
        # https://developer.chrome.com/docs/extensions/reference/browserAction/#tooltip
        tooltip: __MSG_ExtensionName__

        # https://developer.chrome.com/docs/extensions/reference/browserAction/#parts-of-the-ui
        icons:
            "16": assets/icons/icon16.png
            "48": assets/icons/icon48.png
            "128": assets/icons/icon128.png
#
# Permissions
# https://developer.chrome.com/docs/extensions/reference/permissions/
permissions:
    defaults:
        - http://*/*
        - https://*/*
        - cookies
        - privacy
        - storage
        - tabs
        - unlimitedStorage
        - webRequest
        - webRequestBlocking
        - nativeMessaging
        - pageCapture
        - activeTab
    optional:
        #- debugger # The chrome.debugger API serves as an alternate transport for Chrome's remote debugging protocol .
        #- declarativeNetRequest # Grants the extension access to the chrome.declarativeNetRequest API.
        #- devtools # Allows extension to expand Chrome DevTools functionality.
        #- experimental # Canary and Dev channel only. Grants the extension access to chrome.experimental APIs.
        #- geolocation # Allows the extension to use the HTML5 geolocation API.
        #- mdns # Grants the extension access to the chrome.mdns API.
        #- proxy # Grants the extension access to the chrome.proxy API to manage Chrome's proxy settings.
        #- tts # The chrome.tts API plays synthesized text-to-speech (TTS).
        #- ttsEngine # The chrome.ttsEngine API implements a text-to-speech(TTS) engine using an extension.
        #- wallpaper # ChromeOS only. Use the chrome.wallpaper API change the ChromeOS wallpaper.

        

#   // Pick one (or none)
#   "page_action": {...},

#   // Optional
#   "action": ...,
#   "automation": ...,

#   "chrome_settings_overrides": {...},
#   "chrome_url_overrides": {...},
#   "commands": {...},
#   "content_capabilities": ...,
#   "content_security_policy": "policyString",
#   "converted_from_user_script": ...,
#   "current_locale": ...,
#   "declarative_net_request": ...,
#   "devtools_page": "devtools.html",
#   "differential_fingerprint": ...,
#   "event_rules": [{...}],
#   "externally_connectable": {
#     "matches": ["*://*.example.com/*"]
#   },
#   "file_browser_handlers": [...],
#   "file_system_provider_capabilities": {
#     "configurable": true,
#     "multiple_mounts": true,
#     "source": "network"
#   },
#   "host_permissions": ...,
#   "import": [{"id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}],
#   "incognito": "spanning, split, or not_allowed",
#   "input_components": ...,
#   "key": "publicKey",
#   "minimum_chrome_version": "versionString",
#   "nacl_modules": [...],
#   "natively_connectable": ...,
#   "oauth2": ...,
#   "offline_enabled": true,
#   "omnibox": {
#     "keyword": "aString"
#   },
#   "options_page": "options.html",
#   "options_ui": {
#     "chrome_style": true,
#     "page": "options.html"
#   },
#   "platforms": ...,
#   "replacement_web_app": ...,
#   "requirements": {...},
#   "sandbox": [...],
#   "short_name": "Short Name",
#   "storage": {
#     "managed_schema": "schema.json"
#   },
#   "system_indicator": ...,
#   "tts_engine": {...},
#   "update_url": "http://path/to/updateInfo.xml",
#   "web_accessible_resources": [...]
# }