ui:

    # UI Icons
    # @info https://developer.chrome.com/docs/extensions/mv2/manifest/icons/
    icons:
        "16": assets/icons/icon16.png
        "64": assets/icons/icon64.png
        "128": assets/icons/icon128.png